apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-deploy
  labels:
    app: sample-deploy-lbl
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sample-app
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      containers:
      - name: sample-container
        image: ram8243/static-web-app:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: sample-np-service
  labels:
    app: sample-np-app
spec:
  selector:
    app: sample-app

  type: NodePort
  ports:
  - nodePort: 31028
    port: 8080
    targetPort: 8080
